version: "3.7"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "1234:3000"
    volumes:
      - ./Dataset:/dataset
      - grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini

volumes:
  grafana-storage: {}